# このファイルをコピーして secrets.toml にリネームして使う
# secrets.toml は .gitignore に含まれているので GitHub にはアップロードされない
# Streamlit Community Cloud では管理画面の Secrets に同じ内容を貼り付ける

[database]
url = "postgresql://postgres.XXXXXXXXXX:パスワード@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres"
